# Generated by Django 2.2.2 on 2019-06-07 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Flavor Name')),
            ],
            options={
                'verbose_name': 'Flavor',
                'verbose_name_plural': 'Flavors',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Size Name')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Flavor', verbose_name='Flavor')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size', verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='count')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza', verbose_name='Pizza')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('PROCESSING', 'Your order is being processed'), ('COOKING', 'Restaurant is preparing your order'), ('SHIPPING', 'Shipping from Restaurant to the Customer'), ('DELIVERED', 'Delivered to the Customer')], max_length=15, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Order Date')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Update Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Customer', verbose_name='Customer')),
                ('order_items', models.ManyToManyField(to='orders.OrderItem', verbose_name='Order Items')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
