# Generated by Django 2.2.2 on 2019-06-07 21:47

from django.db import migrations, models
import django.db.models.deletion

def set_defaults(apps, schema_editor):
    Pizza = apps.get_model('orders', 'Pizza')
    OrderItem = apps.get_model('orders', 'OrderItem')

    for orderitem in OrderItem.objects.all().iterator():
        orderitem.size = orderitem.pizza.size
        orderitem.flavor = orderitem.pizza.flavor
        orderitem.save()

def reverse_func(apps, schema_editor):
    Pizza = apps.get_model('orders', 'Pizza')
    OrderItem = apps.get_model('orders', 'OrderItem')

    for orderitem in OrderItem.objects.all().iterator():
        pizza = Pizza(flavor=orderitem.flavor, size=orderitem.size)
        pizza.save()
        orderitem.pizza = pizza
        orderitem.save()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190607_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='flavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Flavor', verbose_name='Flavor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size', verbose_name='Size'),
            preserve_default=False,
        ),
        migrations.RunPython(set_defaults, reverse_func),
        migrations.AlterField(
            model_name='orderitem',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Flavor', verbose_name='Flavor'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size', verbose_name='Size'),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='pizza',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
